### PR TITLE
Migrate Display time-sensitive notifications snippets

### PR DESCRIPTION
**Pull request by hamen**
Code snippets are for:
- https://developer.android.com/develop/ui/views/notifications/time-sensitive

List of modifications:
- Time-sensitive page: Migrated 5 Kotlin code snippets to TimeSensitive.kt.
- Time-sensitive page: Added baseline_auto_awesome_24.xml vector drawable resource to resolve notification icon reference.
- Time-sensitive page: Preserved snippet lines with standard exclude tags for compilable state declaration.
- Time-sensitive page: Renamed the `Application` subclass in the channel snippet from `DACapp` to `MyApplication`. The class sits inside the region tag, so the page text needs the same rename.

Snippets not migrated:
- Line 24 because it is an AndroidManifest.xml permission block.
- Line 211 because it is a Java snippet cataloged for removal per Kotlin-first migration guidelines (D15).

### CODE REVIEW

File: compose/snippets/src/main/java/com/example/compose/snippets/notifications/TimeSensitive.kt [hunk 1]
```diff
@@ -0,0 +1,126 @@
...
+
+@Composable
+private fun NotificationPermissionSample() {
+    var hasNotificationPermission by remember { mutableStateOf(false) }
+    // [START android_notifications_time_sensitive_permission]
+    val permissionLauncher = rememberLauncherForActivityResult(
+        contract = ActivityResultContracts.RequestPermission(),
+        onResult = { hasNotificationPermission = it }
+    )
+    // [START_EXCLUDE]
```
Comment (kkuan2011) [inline compose/snippets/src/main/java/com/example/compose/snippets/notifications/TimeSensitive.kt:68]: To simplify, you could replace lines 68-70 with

// ...

File: compose/snippets/src/main/java/com/example/compose/snippets/notifications/TimeSensitive.kt [hunk 2]
```diff
@@ -0,0 +1,126 @@
...
+import androidx.core.app.NotificationCompat
+import com.example.compose.snippets.R
+
+@RequiresApi(Build.VERSION_CODES.O)
+// [START android_notifications_time_sensitive_channel]
+class DACapp : Application() {
+    override fun onCreate() {
+        super.onCreate()
+        val channel = NotificationChannel(
+            CHANNEL_ID,
```
Comment (kkuan2011) [inline compose/snippets/src/main/java/com/example/compose/snippets/notifications/TimeSensitive.kt:49]: Declare CHANNEL_ID explicitly in this file?

I think it's finding the declaration from NotificationsSnippets.kt (in the same package com.example.compose.snippets.notifications) which declares a non-private top-level val CHANNEL_ID = "channelId"

File: compose/snippets/src/main/java/com/example/compose/snippets/notifications/TimeSensitive.kt [hunk 3]
```diff
@@ -0,0 +1,126 @@
...
+import androidx.compose.material3.Text
+import androidx.compose.runtime.Composable
+import androidx.compose.runtime.getValue
+import androidx.compose.runtime.mutableStateOf
+import androidx.compose.runtime.remember
+import androidx.compose.runtime.setValue
+import androidx.core.app.NotificationCompat
+import com.example.compose.snippets.R
+
+@RequiresApi(Build.VERSION_CODES.O)
```
Comment (kkuan2011) [inline compose/snippets/src/main/java/com/example/compose/snippets/notifications/TimeSensitive.kt:43]: Remove this line and the import?

**Review by kkuan2011 — APPROVED** [review]
Once comments are addressed, you can add Aaron for review and remove from "draft" state, thanks!

File: compose/snippets/src/main/java/com/example/compose/snippets/notifications/TimeSensitive.kt (hunk 1 above)
Comment (hamen) [reply compose/snippets/src/main/java/com/example/compose/snippets/notifications/TimeSensitive.kt]: Done in 101e393. Lines 68-70 now collapse into a single `// ...` placeholder inside the region tag.

No `[START_EXCLUDE]` block and no filler statement are necessary, because the lines around the placeholder compile on their own.

File: compose/snippets/src/main/java/com/example/compose/snippets/notifications/TimeSensitive.kt (hunk 2 above)
Comment (hamen) [reply compose/snippets/src/main/java/com/example/compose/snippets/notifications/TimeSensitive.kt:49]: Done in 101e393. `TimeSensitive.kt` now declares `private const val CHANNEL_ID = "channelId"` at the top of the file, outside the region tags.

Your diagnosis was correct. The identifier resolved to the non-private top-level `val CHANNEL_ID` in `NotificationsSnippets.kt`. After I added the local declaration, the two files collided at package scope and the compiler reported an overload resolution ambiguity. I therefore also changed the declaration in `NotificationsSnippets.kt` to `private const val`, which keeps each file self-contained.

File: compose/snippets/src/main/java/com/example/compose/snippets/notifications/TimeSensitive.kt (hunk 3 above)
Comment (hamen) [reply compose/snippets/src/main/java/com/example/compose/snippets/notifications/TimeSensitive.kt]: Done in 101e393. I removed `@RequiresApi(Build.VERSION_CODES.O)` and the `androidx.annotation.RequiresApi` import.

The annotation was redundant, because `minSdk` is 36 in `gradle/libs.versions.toml`, which is much higher than API level 26.

**Review by kkuan2011 — CHANGES_REQUESTED** [review]
Ah actually looks like the build fails:

/home/runner/work/snippets/snippets/compose/snippets/src/main/java/com/example/compose/snippets/notifications/TimeSensitive.kt:120: Error: To call Service.startForeground(), the <service> element of manifest file must have the foregroundServiceType attribute specified [ForegroundServiceType]
        startForeground(notificationId, notification)
        ~~~~~~~~~~~~~~~

   Explanation for issues of type "ForegroundServiceType":
   For targetSdkVersion >= 34, to call Service.startForeground(), the
   <service> element in the manifest file must have the foregroundServiceType
   attribute specified.


https://github.com/android/snippets/actions/runs/35001625484/job/104492132218?pr=1079

File: compose/snippets/src/main/java/com/example/compose/snippets/notifications/TimeSensitive.kt [hunk 4]
```diff
@@ -112,6 +112,7 @@ private class TimeSensitiveNotificationActivity : ComponentActivity() {
 private class TimeSensitiveOngoingService : Service() {
     override fun onBind(intent: Intent?): IBinder? = null
 
+    @SuppressLint("ForegroundServiceType")
```
Comment (alabiaga) [inline compose/snippets/src/main/java/com/example/compose/snippets/notifications/TimeSensitive.kt]: It's a snippet and doesn't need to run but the issue is that the code will compile and i need to verify but willl crash at runtime if it targets Android 14 (API level 34) or higher.

Either declare a fgs type here and in manifest or comment here that we suppress the type but it should defined for a production app.

If doing the former, we can use any type that doesn't require a runtime permission request:

e.g. https://developer.android.com/develop/background-work/services/fgs/service-types#short-service

Comment (hamen) [reply compose/snippets/src/main/java/com/example/compose/snippets/notifications/TimeSensitive.kt]: Declared the type instead of suppressing it. `compose/snippets/src/main/AndroidManifest.xml` now carries `<service android:name=".notifications.TimeSensitiveOngoingService" android:exported="false" android:foregroundServiceType="shortService" />`, together with the `FOREGROUND_SERVICE` and `FOREGROUND_SERVICE_SHORT_SERVICE` permissions. `shortService` needs no runtime permission request, as you suggested.

The `@SuppressLint` is gone. The class is no longer private, because the framework instantiates it.

The region tag content does not change, so the snippet on the page stays the bare `startForeground()` call.

**Comment by hamen** [comment]
@kkuan2011 the `ForegroundServiceType` build error is fixed in d9e66b18. The service declares `android:foregroundServiceType="shortService"` in the manifest, which is what Aaron asked for in his review, so the lint check has nothing left to report and the code no longer throws on API 34 and higher. The branch is also up to date with `main` again.

**Review by kkuan2011 — APPROVED** [review]
Approved, assuming the build passes (Still running)

**Review by alabiaga — APPROVED** [review]

File: compose/snippets/src/main/java/com/example/compose/snippets/notifications/TimeSensitive.kt [hunk 5]
```diff
@@ -0,0 +1,124 @@
...
+import androidx.compose.runtime.mutableStateOf
+import androidx.compose.runtime.remember
+import androidx.compose.runtime.setValue
+import androidx.core.app.NotificationCompat
+import com.example.compose.snippets.R
+
+private const val CHANNEL_ID = "channelId"
+
+// [START android_notifications_time_sensitive_channel]
+class DACapp : Application() {
```
Comment (riggaroo) [inline compose/snippets/src/main/java/com/example/compose/snippets/notifications/TimeSensitive.kt]: Can this be named more appropriately?

**Review by riggaroo — CHANGES_REQUESTED** [review]

File: compose/snippets/src/main/java/com/example/compose/snippets/notifications/TimeSensitive.kt (hunk 5 above)
Comment (hamen) [reply compose/snippets/src/main/java/com/example/compose/snippets/notifications/TimeSensitive.kt]: Done in 8545c28. It is now `MyApplication`, the name the Android documentation uses for an `Application` subclass elsewhere, and the one that matches `SampleStackTracesEnabledApp` in this module.

The class sits inside the region tag, so the page carries `DACapp` until the page text gets the same rename. Say the word if you prefer a different name.

**Review by riggaroo — APPROVED** [review]
